export const EVENTS_CAROUSEL = [
  {
    startTime: new Date(new Date("12/3/24").setHours(6, 0, 0, 0)),
    endTime: new Date(new Date("12/3/24").setHours(10, 0, 0, 0)),
    event: "Tawag ng Tanghalan",
    url: "/events/tawag-ng-tanghalan",
    image: "/images/sample0.jpg",
  },
  {
    startTime: new Date(new Date("12/3/24").setHours(10, 30, 0, 0)),
    endTime: new Date(new Date("12/3/24").setHours(13, 0, 0, 0)),
    event: "Battle of the Bands",
    url: "/events/battle-of-the-bands",
    image: "/images/sample1.jpg",
  },
  {
    startTime: new Date(new Date("12/3/24").setHours(13, 30, 0, 0)),
    endTime: new Date(new Date("12/3/24").setHours(15, 0, 0, 0)),
    event: "Spoken Poetry",
    url: "/events/spoken-poetry",
    image: "/images/sample2.jpg",
  },
  {
    startTime: new Date(new Date("12/4/24").setHours(9, 0, 0, 0)),
    endTime: new Date(new Date("12/4/24").setHours(11, 0, 0, 0)),
    event: "Killer Karaoke",
    url: "/events/killer-karaoke",
    image: "/images/sample3.jpg",
  },
  {
    startTime: new Date(new Date("12/4/24").setHours(12, 0, 0, 0)),
    endTime: new Date(new Date("12/4/24").setHours(14, 0, 0, 0)),
    event: "Laro ng Lahi",
    url: "/events/laro-ng-lahi",
    image: "/images/sample1.jpg",
  },
  {
    startTime: new Date(new Date("12/5/24").setHours(8, 0, 0, 0)),
    endTime: new Date(new Date("12/5/24").setHours(11, 0, 0, 0)),
    event: "Hudyaka Parade of Festivals",
    url: "/events/hudyaka-parade-of-festivals",
    image: "/images/sample2.jpg",
  },
  {
    startTime: new Date(new Date("12/5/24").setHours(12, 0, 0, 0)),
    endTime: new Date(new Date("12/5/24").setHours(14, 0, 0, 0)),
    event: "Mapua Kaloka-like with Talent",
    url: "/events/mapua-kaloka-like-with-talent",
    image: "/images/sample2.jpg",
  },
  {
    startTime: new Date(new Date("12/12/24").setHours(10, 0, 0, 0)),
    endTime: new Date(new Date("12/12/24").setHours(12, 0, 0, 0)),
    event: "Sinag Mr. & Ms. MMCM",
    url: "/events/sinag-mr-and-ms-mmcm",
    image: "/images/sample2.jpg",
  },
];

export const SPORTS_CAROUSEL = [
  {
    sport: "Volleyball",
    url: "/sports/volleyball",
    image: "/images/sports_volleyball.jpg",
    startTime: new Date(new Date("12/6/24").setHours(9, 0, 0, 0)),
    endTime: new Date(new Date("12/6/24").setHours(11, 0, 0, 0)),
  },
  {
    sport: "Basketball",
    url: "/sports/basketball",
    image: "/images/sports_basketball.jpg",
    startTime: new Date(new Date("12/6/24").setHours(12, 0, 0, 0)),
    endTime: new Date(new Date("12/6/24").setHours(14, 0, 0, 0)),
  },
  {
    sport: "Table Tennis",
    url: "/sports/table-tennis",
    image: "/images/sports_table_tennis.jpg",
    startTime: new Date(new Date("12/7/24").setHours(9, 0, 0, 0)),
    endTime: new Date(new Date("12/7/24").setHours(11, 0, 0, 0)),
  },
  {
    sport: "Futsal",
    url: "/sports/futsal",
    image: "/images/sports_futsal.jpg",
    startTime: new Date(new Date("12/7/24").setHours(12, 0, 0, 0)),
    endTime: new Date(new Date("12/7/24").setHours(14, 0, 0, 0)),
  },
  {
    sport: "Badminton",
    url: "/sports/badminton",
    image: "/images/sports_badminton.jpg",
    startTime: new Date(new Date("12/8/24").setHours(9, 0, 0, 0)),
    endTime: new Date(new Date("12/8/24").setHours(11, 0, 0, 0)),
  },
  {
    sport: "Chess",
    url: "/sports/chess",
    image: "/images/sports_chess.jpg",
    startTime: new Date(new Date("12/8/24").setHours(12, 0, 0, 0)),
    endTime: new Date(new Date("12/8/24").setHours(14, 0, 0, 0)),
  },
  {
    sport: "Esports",
    url: "/sports/esports",
    image: "/images/sports_esports.jpg",
    startTime: new Date(new Date("12/9/24").setHours(9, 0, 0, 0)),
    endTime: new Date(new Date("12/9/24").setHours(11, 0, 0, 0)),
  },
];
